In [1]:
import pandas as pd
import requests

In [3]:
df = pd.read_csv('restaurants.csv')

In [4]:
df.head()

,ID,Name,Food Type,Details,Smoking Area,Price Range,City,State
0,1,Ocean's Catch,Mediterranean,"Fresh seafood dishes with a coastal vibe, insp...",Yes,$$$,Houston,TX
1,2,Spice Symphony,American,An orchestra of flavors from around the world ...,Yes,$$$,San Diego,TX
2,3,La Bella Cucina,Chinese,"Authentic Italian cuisine served in a cozy, fa...",No,$$$$,Los Angeles,TX
3,4,The Burger Bar,Mexican,Classic and gourmet burgers with a variety of ...,No,$,Dallas,AZ
4,5,Veggie Garden,Cafe,"A plant-based paradise featuring vibrant, fres...",Yes,$$$,Los Angeles,TX

In [ ]:
def search_picture(term, downloaded_images):
    url = "https://api.pexels.com/v1/search"
    api_key = ""
    headers = { "Authorization": api_key }
    params = { "query": term, "per_page": 1 }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code == 200:
        response = response.json()
        if response['total_results'] > 0:
            url = response['photos'][0]['src']['original']
            filename = url.split('/')[-1]
            if filename in downloaded_images:
                return filename
            response = requests.get(url)
            open(f"images/{filename}", "wb").write(response.content)
            downloaded_images.append(filename)
            return filename

In [6]:
donwloaded_images = []
df = df.assign(Image=df['Name'].apply(lambda x: search_picture(x, donwloaded_images)))
df.head()

,ID,Name,Food Type,Details,Smoking Area,Price Range,City,State,Image
0,1,Ocean's Catch,Mediterranean,"Fresh seafood dishes with a coastal vibe, insp...",Yes,$$$,Houston,TX,pexels-photo-2042591.jpeg
1,2,Spice Symphony,American,An orchestra of flavors from around the world ...,Yes,$$$,San Diego,TX,pexels-photo-29172133.jpeg
2,3,La Bella Cucina,Chinese,"Authentic Italian cuisine served in a cozy, fa...",No,$$$$,Los Angeles,TX,pexels-photo-29132866.jpeg
3,4,The Burger Bar,Mexican,Classic and gourmet burgers with a variety of ...,No,$,Dallas,AZ,pexels-photo-7317354.jpeg
4,5,Veggie Garden,Cafe,"A plant-based paradise featuring vibrant, fres...",Yes,$$$,Los Angeles,TX,pexels-photo-28577205.jpeg

In [7]:
df.to_csv("restaurants.csv", index=False)